AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  DCFFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handler.handler
      Runtime: python3.8
      Tracing: Active
      Events:
        DCFRequest:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  StockPrice:
    Description: "API Gateway endpoint URL for Prod stage for Stock Price function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"